- name: install nginx
  zypper:
    name: nginx
    state: present
  notify:
    - restart nginx

- name: systemd nginx
  systemd:
    name: nginx
    enabled: yes
    state: started

- name: creat file index.html
  ansible.builtin.file:
    path: /srv/www/htdocs/index.html
    mode: '0644'
    state: touch

- name: import ip server
  lineinfile:
    path: "/srv/www/htdocs/index.html"
    line: '{{ansible_all_ipv4_addresses}}'

- name: configuring firewall
  firewalld:
    port: 80/tcp
    permanent: yes
    state: enabled
  notify:
    - reload firewalld

